
Map<String, String> countryFlagMap={
  'American': 'https://www.themealdb.com/images/icons/flags/big/64/us.png',
  'British': 'https://www.themealdb.com/images/icons/flags/big/64/gb.png',
  'Canadian': 'https://www.themealdb.com/images/icons/flags/big/64/ca.png',
  'Chinese': 'https://www.themealdb.com/images/icons/flags/big/64/cn.png',
  'Croatian': 'https://www.themealdb.com/images/icons/flags/big/64/hr.png',
  'Dutch': 'https://www.themealdb.com/images/icons/flags/big/64/nl.png',
  'Egyptian': 'https://www.themealdb.com/images/icons/flags/big/64/eg.png',
  'French': 'https://www.themealdb.com/images/icons/flags/big/64/fr.png',
  'Greek': 'https://www.themealdb.com/images/icons/flags/big/64/gr.png',
  'Indian': 'https://www.themealdb.com/images/icons/flags/big/64/in.png',
  'Irish': 'https://www.themealdb.com/images/icons/flags/big/64/ie.png',
  'Italian': 'https://www.themealdb.com/images/icons/flags/big/64/it.png',
  'Jamaican': 'https://www.themealdb.com/images/icons/flags/big/64/jm.png',
  'Japanese': 'https://www.themealdb.com/images/icons/flags/big/64/jp.png',
  'Kenyan': 'https://www.themealdb.com/images/icons/flags/big/64/ke.png',
  'Malaysian': 'https://www.themealdb.com/images/icons/flags/big/64/my.png',
  'Mexican': 'https://www.themealdb.com/images/icons/flags/big/64/mx.png',
  'Moroccan': 'https://www.themealdb.com/images/icons/flags/big/64/ma.png',
  'Polish': 'https://www.themealdb.com/images/icons/flags/big/64/pl.png',
  'Portuguese': 'https://www.themealdb.com/images/icons/flags/big/64/pt.png',
  'Russian': 'https://www.themealdb.com/images/icons/flags/big/64/ru.png',
  'Spanish': 'https://www.themealdb.com/images/icons/flags/big/64/es.png',
  'Thai': 'https://www.themealdb.com/images/icons/flags/big/64/th.png',
  'Tunisian': 'https://www.themealdb.com/images/icons/flags/big/64/tn.png',
  'Turkish': 'https://www.themealdb.com/images/icons/flags/big/64/tr.png',
  'Unknown': 'https://www.pngrepo.com/png/398539/64/unknown-flag.png',
  'Vietnamese': 'https://www.themealdb.com/images/icons/flags/big/64/vn.png',
};

